- name: Update/patch the CI
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    silent: false
    become_override: false
    ACTION: "INSTALL" # INSTALL, UNINSTALL, UPDATE
    
  tasks:
    - name: UGather facts
      include_role:
        name: roles/gather_facts

