- name: Update/patch the automotive-image-builder host
  hosts: aib-hosts
  vars:
    # set the following to control the install/uninstall process
    silent: false
    become_override: false
    ACTION: "INSTALL" # INSTALL, UNINSTALL, UPDATE
  
  tasks:
    - name: Update/patch/uninstall the automotive-image-builder host
      include_role:
        name: roles/prepare_aib
