# Implement your install deployment tasks here
# -------------------------------------------------

- name: Remove the builder directory
  become: true
  ansible.builtin.file:
    path: "{{ work_dir }}/{{ build_dir }}"
    state: absent

- name: Create builder sub-directories
  become: true
  ansible.builtin.file:
    path: "{{ work_dir }}/{{ build_dir }}/{{ item }}"
    state: directory
  with_items:
    - "builds"
    - ".mpp-cache"

- name: Clone the repo
  become: true
  ansible.builtin.git:
    repo: "{{ aib_repo }}"
    version: "{{ aib_branch }}"
    dest: "{{ work_dir }}/{{ build_dir }}/{{ aib_dest }}"
    single_branch: yes
