# Implement your install deployment tasks here
# -------------------------------------------------

- name: remove the builder directory
  become: true
  ansible.builtin.file:
    path: "{{ work_dir }}/{{ build_dir }}"
    state: absent

- name: create builder sub-directories
  become: true
  ansible.builtin.file:
    path: "{{ work_dir }}/{{ build_dir }}/{{ item }}"
    state: directory
  with_items:
    - "builds"
    - ".mpp-cache"

- name: clone the repo
  become: true
  ansible.builtin.git:
    repo: "{{ aib_repo }}"
    version: "{{ aib_branch }}"
    dest: "{{ work_dir }}/{{ build_dir }}/{{ aib_dest }}"
    single_branch: yes

- name: additional Python packages
  become: true
  shell: |
    pip install boto3