# Implement your post-install deployment tasks here
# -------------------------------------------------

- name: create AWS config location
  ansible.builtin.file:
    path: "~/.aws"
    state: directory

- name: copy AWS config
  ansible.builtin.template:
    src: "../templates/config.j2"
    dest: "~/.aws/config"
    mode: "0644"

- name: copy AWS credentials
  ansible.builtin.template:
    src: "../templates/credentials.j2"
    dest: "~/.aws/credentials"
    mode: "0644"