# Implement your install deployment tasks here
# -------------------------------------------------

- name: create machine set
  k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - arm-metal-machine-set.yml.j2