# Implement your install deployment tasks here
# -------------------------------------------------

- name: create cluster role and binding
  k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - jumpstarter-clusterrole.yml
    - jumpstarter-rolebinding.yml

- name: create the application
  k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - jumpstarter-application.yml.j2

- name: create secret
  kubernetes.core.k8s:
    state: present
    kind: Secret
    name: jumpstarter-secret
    namespace: "{{ jumpstarter_namespace }}"
    definition:
      metadata:
        name: jumpstarter-secret
      type: Opaque
      data:
        token: "{{ jumpstarter_token }}"
