# Implement your pre-install deployment tasks here
# -------------------------------------------------

- name: create jumpstarter namespace
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    name: "{{ jumpstarter_namespace }}"
    definition:
      metadata:
        labels:
          argocd.argoproj.io/managed-by: openshift-gitops
