# Implement your uninstall deployment tasks here
# -------------------------------------------------

- name: uninstall the Jumpstarter operator
  shell: oc delete apps jumpstarter -n openshift-gitop

- name: delete the Jumpstarter qemu exporter namespace
  shell: oc delete namespace "{{ jumpstarter_qemu_exporter_namespace }}"

- name: delete the Jumpstarter namespace
  shell: oc delete namespace "{{ jumpstarter_namespace }}"

- name: delete the oidc-reviewer cluster role binding
  shell: oc delete clusterrolebindings.rbac.authorization.k8s.io oidc-reviewer
