#!/bin/bash

set -e

cd /home/workspace

sudo podman run --rm -ti --net=host --privileged \
  -v /run/udev:/run/udev -v /dev:/dev -v /root/.kube/config:/root/.kube/config -v "$PWD":"$PWD" \
  quay.io/rhadp-example-repos/jumpstarter:latest \
  /bin/bash -c "cd $PWD/; jmp run --exporter-config ./outpost-default-exporter.yaml"