# Implement your install deployment tasks here
# -------------------------------------------------

- name: create vault secrets for aib-builder host access
  ignore_errors: true
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_namespace }}"
    pod: vault-0
    command: "{{ item }}"
  loop:
    - "vault kv put kv/secrets/janusidp/aib/user value={{ aib_builder_user }}"
    - "vault kv put kv/secrets/janusidp/aib/password value={{ aib_builder_password }}"
    - "vault kv put kv/secrets/janusidp/aib/host value={{ aib_builder_host }}"

- name: create vault secrets for AWS/S3
  ignore_errors: true
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_namespace }}"
    pod: vault-0
    command: "{{ item }}"
  loop:
    - "vault kv put kv/secrets/janusidp/aws/access_key_id value={{ aws_access_key_id }}"
    - "vault kv put kv/secrets/janusidp/aws/secret_access_key value={{ aws_secret_access_key }}"
    - "vault kv put kv/secrets/janusidp/aws/default_region value={{ aws_default_region }}"
    