# Implement your install deployment tasks here
# -------------------------------------------------

- name: build Badgerd SDWireC
  ansible.builtin.import_tasks: build_sdwire.yml
  when: install_sdwire

- name: build YKUSH 
  ansible.builtin.import_tasks: build_ykush.yml
  when: install_ykush

- name: pull the latest jumpstarter container
  become: true
  shell: podman pull {{ container_image }}