- name: install the oc client
  become: true
  shell: |
    curl {{ oc_client_url }} -o oc.tar.gz
    tar xvf oc.tar.gz
    sudo mv oc /usr/local/bin/
    sudo mv kubectl /usr/local/bin/
    rm oc.tar.gz
  args:
    chdir: "{{ work_dir }}"

- name: authenticate to the cluster (normal user)
  shell: oc login https://api.{{ cluster_base_domain }}:6443 --username=admin --password={{ cluster_generic_password }} --insecure-skip-tls-verify=true

- name: authenticate to the cluster (sudo user)
  become: true
  shell: oc login https://api.{{ cluster_base_domain }}:6443 --username=admin --password={{ cluster_generic_password }} --insecure-skip-tls-verify=true