# Implement your post-install deployment tasks here
# -------------------------------------------------

# create the example exporter if it does not exist first !

- name: create the default exporters
  become: true
  shell: |
    podman run --rm -ti --net=host --privileged \
      -v /run/udev:/run/udev -v /dev:/dev -v /root/.kube/config:/root/.kube/config -v "$PWD":"$PWD" \
      quay.io/rhadp-example-repos/jumpstarter:latest \
      /bin/bash -c "cd $PWD/; jmp admin create exporter outpost-{{ item }} -l lab2255/board {{ item }} --save --out ./outpost-{{ item }}-exporter.yaml"
  args:
    chdir: "{{ work_dir }}"
  with_items:
    - "default"
    - "rpi4"
    - "ti"

- name: read the exporter config
  slurp:
    src: "{{ work_dir }}/outpost-default-exporter.yaml"
  register: exporter_file

- name: parse the exporter config
  set_fact:
    exporter_config: "{{ exporter_file.content | b64decode | from_yaml }}"

- name: create vault secrets for jumpstarter
  ignore_errors: true
  delegate_to: localhost
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_namespace }}"
    pod: vault-0
    command: "{{ item }}"
  loop:
    - "vault kv put kv/secrets/janusidp/jumpstarter/token value={{ exporter_config.token }}"

- name: patch the exporter configs
  become: true
  ansible.builtin.template:
    src: "../templates/{{ item }}-exporter.yaml.j2"
    dest: "{{ work_dir }}/outpost-{{ item }}-exporter.yaml"
    mode: "0755"
  with_items:
    - "default"
    - "rpi4"
    - "ti"

- name: create systemd services
  ansible.builtin.import_tasks: create_systemd.yml
