# Implement your post-install deployment tasks here
# -------------------------------------------------

# create the example exporter if it does not exist first !

- name: create the mock exporter
  become: true
  shell: |
    podman run --rm -ti --net=host --privileged \
      -v /run/udev:/run/udev -v /dev:/dev -v /etc/jumpstarter:/etc/jumpstarter -v /root/.kube/config:/root/.kube/config \
      quay.io/rhadp-example-repos/jumpstarter:latest \
      jmp admin create exporter outpost-mock -l shadowcar/board mock --save

- name: create the mock client
  become: true
  shell: |
    podman run --rm -ti --net=host --privileged \
      -v /run/udev:/run/udev -v /dev:/dev -v /etc/jumpstarter:/etc/jumpstarter -v /root/.kube/config:/root/.kube/config \
      quay.io/rhadp-example-repos/jumpstarter:latest \
      jmp admin create client outpost-mock --save --unsafe