# Implement your pre-install deployment tasks here
# -------------------------------------------------

- name: install additional packages
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - traceroute
      - podman
      - git

- name: install development packages
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - build-essential
      - libftdi1-dev
      - libpopt-dev
      - cmake
      - pkg-config
      - libusb-1.0-0
      - libusb-1.0-0-dev

- name: remove the working directory
  become: true
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: absent

- name: re-create the working dir
  become: true
  ansible.builtin.file:
    path: "{{ work_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: install the oc client
  become: true
  shell: |
    curl {{ oc_client_url }} -o oc.tar.gz
    tar xvf oc.tar.gz
    sudo mv oc /usr/local/bin/
    sudo mv kubectl /usr/local/bin/
    rm oc.tar.gz
  args:
    chdir: "{{ work_dir }}"


  