# Implement your post-install deployment tasks here
# -------------------------------------------------

- name: remove local backstage config file
  file:
    path: "roles/patch_developer_hub/templates/app-config.yaml"
    state: absent