# Implement your install deployment tasks here
# -------------------------------------------------

- name: create the rhadp application
  k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - rhadp-bootstrap.yml.j2