# Implement your install deployment tasks here
# -------------------------------------------------

- name: install pipeline assets
  include_tasks:
    file: ./install_pipeline_assets.yml
    apply:
      become: "{{ become_override | bool }}"